Fixed Linter Issue.

diff --git a/.github/workflows/bookstore_ui_CI.yaml b/.github/workflows/bookstore_ui_CI.yaml
--- a/.github/workflows/bookstore_ui_CI.yaml
+++ b/.github/workflows/bookstore_ui_CI.yaml
@@ -1,83 +1,80 @@
 name: bookstore_ui CI
 
 on:
-    push: 
-        branches:
-            - master
-    pull_request:
-        branches:
-            - master
+  push:
+    branches:
+      - master
+  pull_request:
+    branches:
+      - master
 
 env:
-    cache-node_modules-name: npm_packages 
-              
+  cache-node_modules-name: npm_packages
+
 jobs:
-    linting:
-        name: Linter
-        runs-on: ubuntu-latest
+  linting:
+    name: Linter
+    runs-on: ubuntu-latest
 
-        steps:
-            - name: Set up Node.js
-              uses: actions/setup-node@v2
-              with:
-                node-version: '14'
+    steps:
+      - name: Set up Node.js
+        uses: actions/setup-node@v2
+        with:
+          node-version: '14'
 
-            - name: Checkout code
-              uses: actions/checkout@v2
-  
-            - name: Caching dependencies
-              id: cache-node_modules
-              uses: actions/cache@v2
-              with:
-                # npm cache files are stored in `~/.npm` on Linux/macOS
-                path: ~/.npm
-                key: ${{ runner.os }}-${{env.cache-node_modules-name}}-${{ hashFiles('**/package-lock.json') }}
-                restore-keys: |
-                    ${{ runner.os }}-${{env.cache-node_modules-name}}-
-            
-            - name: Install dependencies
-              if: steps.cache-node_modules.outputs.cache-hit != 'true'  # Run only if cache is not found
-              run: npm ci        
-            
-            - name: Run Prettier Linter
-              run: |
-                echo "Running Prettier Linter"
-                npm run lint
-                lint_exit_code=$?
-                if [ $lint_exit_code -ne 0 ]; then
-                    echo "Linting failed. Exiting pipeline..."
-                    exit $lint_exit_code
-                fi
+      - name: Checkout code
+        uses: actions/checkout@v2
 
-    Tests:
-        name: Tests
-        runs-on: ubuntu-latest
-        needs: [linting]
+      - name: Caching dependencies
+        id: cache-node_modules
+        uses: actions/cache@v2
+        with:
+          # npm cache files are stored in `~/.npm` on Linux/macOS
+          path: ~/.npm
+          key: ${{ runner.os }}-${{env.cache-node_modules-name}}-${{ hashFiles('**/package-lock.json') }}
+          restore-keys: |
+            ${{ runner.os }}-${{env.cache-node_modules-name}}-
 
-        steps:
-            - name: Set up Node.js
-              uses: actions/setup-node@v2
-              with:
-                node-version: '14'
+      - name: Install dependencies
+        if: steps.cache-node_modules.outputs.cache-hit != 'true' # Run only if cache is not found
+        run: npm ci
 
-            - name: Checkout code
-              uses: actions/checkout@v2
+      - name: Run Prettier Linter
+        run: |
+          echo "Running Prettier Linter"
+          npm run lint
+          lint_exit_code=$?
+          if [ $lint_exit_code -ne 0 ]; then
+              echo "Linting failed. Exiting pipeline..."
+              exit $lint_exit_code
+          fi
 
-            - name: Restore cache
-              id: restore-cache-node_modules  
-              uses: actions/cache@v2
-              with:
-                path: ~/.npm
-                key: ${{ runner.os }}-${{env.cache-node_modules-name}}-${{ hashFiles('**/package-lock.json') }}
-                restore-keys: |
-                  ${{ runner.os }}-${{env.cache-node_modules-name}}-
-            
-            - name: Install dependencies
-              if: steps.restore-cache-node_modules.outputs.cache-hit != 'true'  # Run only if cache is not found
-              run: npm ci
-            
-            - name: Running Tests
-              run: npm run test:coverage-report
-              
+  Tests:
+    name: Tests
+    runs-on: ubuntu-latest
+    needs: [linting]
 
-    
+    steps:
+      - name: Set up Node.js
+        uses: actions/setup-node@v2
+        with:
+          node-version: '14'
+
+      - name: Checkout code
+        uses: actions/checkout@v2
+
+      - name: Restore cache
+        id: restore-cache-node_modules
+        uses: actions/cache@v2
+        with:
+          path: ~/.npm
+          key: ${{ runner.os }}-${{env.cache-node_modules-name}}-${{ hashFiles('**/package-lock.json') }}
+          restore-keys: |
+            ${{ runner.os }}-${{env.cache-node_modules-name}}-
+
+      - name: Install dependencies
+        if: steps.restore-cache-node_modules.outputs.cache-hit != 'true' # Run only if cache is not found
+        run: npm ci
+
+      - name: Running Tests
+        run: npm run test:coverage-report
